spring:
  application:
    name: jupiter-bs-api
  profiles:
    active: local #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 50MB #限制文件上传大小为50M
      max-request-size: 50MB
  jackson:
    default-property-inclusion: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: false
  params: count=countsql
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  secret: abas-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)



